### ISSUE TITLE
DeprecationWarning : use options instead of chrome_options

### ISSUE THREAD

**Issue by caleberi** [dhananjay1210/Leetcode-Downloader#4]
How do i fix this error , after following all the list step :
```
DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\leetcode_downloader.py", line 192, in <module>
    driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```
I also filled the required info but got that error

**Comment by dhananjay1210** [comment]
Thanks for pointing out the issue. I am looking on it.

**Comment by dhananjay1210** [comment]
@caleberi Please make sure you put all the code files and chromedriver.exe in the same folder. I have updated the codebase. Kindly follow the medium article and let me know whether the issue is resolved or not.

**Comment by caleberi** [comment]
@dhananjay1210  I did put the driver in the same directory as the downloader and add it to my path but currently it is giving error the chromium version 91.X should be used but i did download that exact version from the website but It still giving error that my version is 90.X .

**Comment by dhananjay1210** [comment]
@caleberi On [ChromeDriver](https://chromedriver.chromium.org/downloads) website, I can see 2 different ChromeDriver for Chrome90.X
If you are using **Chrome version 90**, please download **ChromeDriver 91**.0.4472.19
If you are using **Chrome version 90**, please download **ChromeDriver 90**.0.4430.24

It seems like a compatibility issue between Chrome and ChromeDriver versions (especially for 91.X and 90.X). I use 89.X and it works smoothly :)

**Comment by caleberi** [comment]
@dhananjay1210,  thanks I will try that and get back to you

**Comment by Zhaoyu-W** [comment]
I also had the same error on mac. Already downloaded the latest version **104.0.5112.79** and put chromedriver in the same folder.


```
/Users/zhaoyu/Programming/Leetcode-Downloader/leetcode_downloader.py:185: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)
Traceback (most recent call last):
  File "/Users/zhaoyu/Programming/Leetcode-Downloader/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Users/zhaoyu/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/zhaoyu/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhaoyu/Programming/Leetcode-Downloader/leetcode_downloader.py", line 185, in <module>
    driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)
  File "/Users/zhaoyu/Programming/Leetcode-Downloader/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/Users/zhaoyu/Programming/Leetcode-Downloader/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/Users/zhaoyu/Programming/Leetcode-Downloader/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
```

**Comment by GustavoAdame** [comment]
Just replace driver = webdriver.Chrome()
